"""Add is_approved and submitted_by to Doctor

Revision ID: 495362d05bdd
Revises: 
Create Date: 2026-10-05 18:39:57.596477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495362d05bdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('submitted_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['submitted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('submitted_by')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
